### ISSUE TITLE
DBMigrationService.swift line 80

### ISSUE THREAD

**Issue by gnosis-safe-ios-crashlytics** [gnosis/safe-ios-legacy#1009]
#### in 

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/gnosis/ios/apps/io.gnosis.safe/issues/85230f747f8394d403f3cdda58a2d050?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/gnosis/ios/apps/io.gnosis.safe/issues/85230f747f8394d403f3cdda58a2d050?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by DmitryBespalov** [comment]
this crash is from 1.2.0 version - not supported anymore.
