### ISSUE TITLE
WalletConnect library relay call failed

### ISSUE THREAD

**Issue by gnosis-safe-ios-crashlytics** [gnosis/safe-ios-legacy#1036]
#### in 

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/gnosis/ios/apps/io.gnosis.safe.prerelease/issues/66eb5c8bb1c7e45c9b849276041f079a?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/gnosis/ios/apps/io.gnosis.safe.prerelease/issues/66eb5c8bb1c7e45c9b849276041f079a?utm_medium=service_hooks-github&utm_source=issue_impact)

Error happened when app was in background.

App could not relay the request (some http error...) and should have forwarded it to the dapp.

Check that the code does indeed forwards the errors back to the dapp.

**Comment by sche** [comment]
I checked. All good.
