### ISSUE TITLE
UI glitch in token search (maybe due to iOS13)

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-ios-legacy#1065]
**Describe the bug**
On the token list, the background of the text input field is black.

Please note I have the iOS 13 beta installed. This might be the reason.

**To Reproduce**
Go to token search

**Expected behavior**
Not black.

**Screenshots**
![File (1)](https://user-images.githubusercontent.com/1380529/62850590-9f6f9980-bce3-11e9-8687-c8d6af3bade0.jpg)

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - iOS Version: 13.0
 - App Version: 1.5.0 (2) mainnet prod

**Comment by DmitryBespalov** [comment]
this is ios 13, we'll fix it together with other glitches in iOS 13
