### ISSUE TITLE
Crash when trying to notify Authenticator in Send Review

### ISSUE THREAD

**Issue by gnosis-safe-ios-crashlytics** [gnosis/safe-ios-legacy#1068]
#### in 

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/gnosis/ios/apps/io.gnosis.safe/issues/696cb42449661ddc6243927efa376f15?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/gnosis/ios/apps/io.gnosis.safe/issues/696cb42449661ddc6243927efa376f15?utm_medium=service_hooks-github&utm_source=issue_impact)

The app is showing Review screen and was trying to notify the authenticator and crashed.

**Comment by DmitryBespalov** [comment]
This is crash happening on one user device who restored the phone from iCloud backup. After restoration, the Keychain was not restored (it is only restored from encrypted backup). This led to crashes because the phone can't find the keys anymore. This is addressed in #1106
