### ISSUE TITLE
WalletConnect Support

### ISSUE THREAD

**Issue by ricburton** [gnosis/safe-ios-legacy#110]
If we put the time in would you be open to adding this? 

www.WalletConnect.org

**Comment by tschubotz** [comment]
Right now, we still have our static setup, where every user needs to set up the Safe with their mobile phone AND connect it to a Chrome extension. Thereby we have bridged the gap between mobile and desktop already.
However, I think in the future we'll probably allow for different setups that don't necessarily involve a Chrome extension. Then WalletConnect could definitely make sense.

**Comment by DmitryBespalov** [comment]
This will be worked on as part of the future roadmap. Closing for now.

**Comment by ricburton** [comment]
🎉🎉🎉

Richard
