### ISSUE TITLE
After restoring from iCloud, the app works but can't send any transactions (it crashes instead)

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-ios-legacy#1106]
After restoring from iCloud, the Keychain is not restored, so the app can't send any transactions - it crashes. In this case, the database is still there. The app shall notify the user that there is a problem and the app must be reinstalled.

Checks to perform on startup:

- can access the password in the Keychain?

  - "Error. Failed to check the password. Please restore the device from encrypted backup or reinstall the app and recover the safe."

- can access the device's keys in the Keychain?

  - "Error. Failed to use the device key. Transactions submission will not work. Please restore the device from encrypted backup or reinstall the app and recover the safe."

- are the local addresses still owners of the safe in the blockchain?

  - "Error. This device is no longer a safe owner. Please reinstall the app and recover the safe."
  - "Error. The known authenticator is no longer a safe owner. Please replace the authenticator or disconnect it."
  - "Error. The backup phrase is no longer valid for the safe. Please replace the backup phrase."
  - "Error. The safe has unexpected configuration. Please reinstall the app and recover the safe."

- does the safe still exist in the backend database? (if not, we may be in a wrong network configuration) - show error explaining that and suggesting to remove and recover the safe.

  - "Error. The safe is not supported anymore. Please reinstall the app and recover the safe."

**Comment by tschubotz** [comment]
> "Error. Failed to check the password. Please restore the device from encrypted backup or reinstall the app and recover the safe."

That means the device password cannot be found in the keychain, right? I feel like "Failed to check the password" sounds not ideal. How about "Failed to locate device password in Keychain." or something like this? To be a bit more explicit?

> "Error. Failed to use the device key. Transactions submission will not work. Please restore the device from encrypted backup or reinstall the app and recover the safe."

Same here, how about "Failed to locate device key."?

> "Error. This device is no longer a safe owner. Please reinstall the app and recover the safe."

Could we also allow them to remove the Safe from the device and then just let them recover it without reinstalling? Or is the reinstall required?

> "Error. The backup phrase is no longer valid for the safe. Please replace the backup phrase."

How do you find out about this? Also I would call it "recovery phrase". I think that's the term we use in other places (?)

> "Error. The safe is not supported anymore. Please reinstall the app and recover the safe."

How about adding the info about the network. "Error. The safe is not supported anymore. Please check your network or reinstall the app and recover the safe."
