### ISSUE TITLE
Diagnostic false positive alert

### ISSUE THREAD

**Issue by gnosis-safe-ios-crashlytics** [gnosis/safe-ios-legacy#1136]
#### in 

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/gnosis/ios/apps/io.gnosis.safe/issues/fcdab0e2ff180c5754c9ded3a83bf08a?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/gnosis/ios/apps/io.gnosis.safe/issues/fcdab0e2ff180c5754c9ded3a83bf08a?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by DmitryBespalov** [comment]
most probably false positivie because the device is in the background and the diagnostic tries to get the key from the keychain.
