### ISSUE TITLE
App crashes when switching payment method during Safe creation

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-ios-legacy#1267]
**Describe the bug**
App crashes when switching payment method during Safe creation

**To Reproduce**
(During Safe creation)
> ups I think there is a bug, when I change the payment method to OWL the App closes, have to restart all from the beginning

**Expected behavior**
No crash.

**Smartphone (please complete the following information):**
 - Device: iPhone 7 plus
 - iOS Version: 13.1.2
 - App Version: 1.8.1 (1) Production Mainnet

**Additional context**
Cata reported this originally. She'll have more info if needed.

**Comment by DmitryBespalov** [comment]
should be fixed now
