### ISSUE TITLE
App crashes on startup after installation

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-ios-legacy#1269]
**Describe the bug**
App crashes on startup after installation

**To Reproduce**
1. Install Safe app
2. Open app
-> Crash

**Expected behavior**
No crash

**Screencast**
https://gnosisinc.slack.com/archives/C63LQTGNB/p1572963695009500

**Smartphone (please complete the following information):**
 - Device: iPhone 6
 - iOS Version: iOS 12.4.3
 - App Version: ?

**Additional context**
Reported by Stefana. She'll have more info if needed.

**Comment by DmitryBespalov** [comment]
This also happened to a user with iPhone 6 Plus, iOS 12.4.3, with App Version 1.8.1 (app store)
