### ISSUE TITLE
EncryptionService.swift line 381

### ISSUE THREAD

**Issue by gnosis-safe-ios-crashlytics** [gnosis/safe-ios-legacy#1298]
#### in 

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/gnosis/ios/apps/io.gnosis.safe/issues/d29ae7448ac9f983534b68441e2221d8?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/gnosis/ios/apps/io.gnosis.safe/issues/d29ae7448ac9f983534b68441e2221d8?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by DmitryBespalov** [comment]
Hypothetically reproducible scenario:
1. Send ETH - continue
2. Switch off the internet so that the review can't get an estimation.
3. Sign with the Keycard nevertheless
