### ISSUE TITLE
DBAbstractRepository.swift line 54

### ISSUE THREAD

**Issue by gnosis-safe-ios-crashlytics** [gnosis/safe-ios-legacy#1310]
#### in 

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/gnosis/ios/apps/io.gnosis.safe.prerelease/issues/bf27d7f4d1e2004370d30214d2739480?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/gnosis/ios/apps/io.gnosis.safe.prerelease/issues/bf27d7f4d1e2004370d30214d2739480?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by tschubotz** [comment]
This was most likely me. I'm on the latest Rinkeby iOS app from Testflight and I cannot login to the Safe.

Everytime, I authenticate via fingerprint / password, the app crashes. Let me know if you need more info or need my device for debugging. @DmitryBespalov

**Comment by DmitryBespalov** [comment]
@tschubotz the rinkeby version is not updated with the latest hotfix, so I'm closing this now. Will update the testflight for the upcoming 1.10.0
