### ISSUE TITLE
RecoveryDomainService.swift line 202

### ISSUE THREAD

**Issue by gnosis-safe-ios-crashlytics** [gnosis/safe-ios-legacy#1373]
#### in 

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/gnosis/ios/apps/io.gnosis.safe.adhoc/issues/d38df7d59b9358a02724b159caa811a1?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/gnosis/ios/apps/io.gnosis.safe.adhoc/issues/d38df7d59b9358a02724b159caa811a1?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by DmitryBespalov** [comment]
happens in `RecoveryDomainService.resume()` when transaction not found (nil)
