### ISSUE TITLE
Error when using oasis.app

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-ios-legacy#1376]
**Describe the bug**
I'm trying to deposit DAI to earn saving on my DAI but there seems to be an error.

**To Reproduce**
1. Go to https://oasis.app/save (I'm connected via WalletConnect)
2. Enter Dai amount
3. Hit "Deposit"
4. I get the notification on my phone
5. I submit on my phone
6. I get an error "Application submitted invalid request to server. Try again later."
7. I cannot continue 😭 

**Expected behavior**
It works

**Screenshots**
![IMG_22C9B8E3BE93-1](https://user-images.githubusercontent.com/1380529/70898099-49459680-1ff4-11ea-9440-c0c78f3a7966.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - iOS Version: 13.2
- App version: 1.11.0 (3) Production Mainnet

**Comment by sche** [comment]
Could not reproduce it. But I found the related error in our logs and created a linked issue.
