### ISSUE TITLE
App crashes after update to 1.13.0

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-ios-legacy#1409]
**Describe the bug**
After updating my Safe Rinkeby app to the latest version available via Testflight, my app crashes after unlocking the Safe.

**To Reproduce**
I updated via Testflight
1. Unlock app via touch ID
2. 💥 

**Expected behavior**
No crash

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - iOS Version: 13.3
 - App Version 1.13.0 Rinkeby

**Comment by sche** [comment]
@tschubotz the issue is that you installed some old internal version (1.9.0 (1)) probably, that had a bug in a db scheme. We did not do a proper migration, as it was an internal version, but we did a new version (1.9.0 (3)). So now you need to re-install the rinkeby app.
