### ISSUE TITLE
Create password glitch

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-ios-legacy#335]
**Describe the bug**
We have the following password requirements: 
- min 8 chars
- min 1 number and min 1 letter
- no triple chars

I cannot advance when choosing `rich987ard` as a password

**To Reproduce**
- Clean install of app
- Enter `rich987ard` as password
-> I cannot continue
(I can continue as soon as I enter an uppcase letter though)

**Expected behavior**
I can use this password since it clearly satisfies the pw requirements :)

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - iOS Version: 12.1
 - App Version: 0.8.0 (4) from testflight

**Additional context**
-

**Comment by DmitryBespalov** [comment]
Workaround: please use one capital letter in addition to those chars

**Comment by okwme** [comment]
bump

**Comment by DmitryBespalov** [comment]
fixed
