### ISSUE TITLE
browser extension doesn't progress

### ISSUE THREAD

**Issue by okwme** [gnosis/safe-ios-legacy#337]
i've had the browser extension since it was first announced but was unable to use it without access to an android. now that i've got the testflight ios app installed i've connected the browser extension to the app and successfully moved money into my safe. I'm attempting to make a new transfer of eth from the safe, and after confirming i am at the "Review tranaction" page with a loader telling me "awaiting confirmation". My browser app hasn't updated past the page telling me to download the android app or show the qr code. should the confirmation happen automatically or would it be waiting for me on another part of the chrome extension? i've hit "re-send confirmation" a few times with the extension open and unlocked as well as closed but see no difference.

**Comment by DmitryBespalov** [comment]
Good day Billy, thank you for your report. As far as I understood, you were able to connect browser extension with the safe, but then when you made a transfer, the browser didn't receive confirmation, is that correct?

**Comment by okwme** [comment]
Hi Dmitry,
Yes that's correct, after a successful pair i was unable to get a confirmation.

**Comment by okwme** [comment]
after uninstalling and reinstalling everything it seems to work now!
