### ISSUE TITLE
change chrome extension association

### ISSUE THREAD

**Issue by okwme** [gnosis/safe-ios-legacy#338]
as an attempt to bypass my issue of transferring eth i tried uninstalling and reinstalling my chrome extension. I'm no longer sure whether my browser is actually associated with my wallet and don't see an option to add edit or remove my mobile wallet browser wallet association. is this possible?

**Comment by DmitryBespalov** [comment]
Good day Billy, thank you for using safe app. Unfortunately, now it is not possible to add or remove browser extension after the safe was already created. Sorry for the inconvenience. This feature is in our next release.

**Comment by DmitryBespalov** [comment]
Hi, update on this. We had to postpone this feature for one more release because the priority changed.

**Comment by DmitryBespalov** [comment]
This will be handled as part of gnosis/safe#60
