### ISSUE TITLE
Create Password- The user has to put a capital letter to create a password

### ISSUE THREAD

**Issue by lvazq** [gnosis/safe-ios-legacy#342]
Pre conditions:
-Iphone 7 and Iphone 10

Steps to reproduce:
1- Enter to the APP 
2- Select 'Setup password'
3- Tap on Agree
4- Create a password with seven letters and one number
5- Observe

Expected result:
The user continue to the next screen

Actual result:
The user must put a capital letter in the password

Environment:
iOS 12.1

https://drive.google.com/open?id=11-ZkmZb1L9uez-vGXWAFf2ssFoXa-f9Y

**Comment by DmitryBespalov** [comment]
Good day lvazq, thank you for your report. This issue was already reported here: #335. I'll close this issue.
