### ISSUE TITLE
The requirement "No triple character" works wrong

### ISSUE THREAD

**Issue by damiandragobetzky** [gnosis/safe-ios-legacy#344]
When you repeat a character three or more times, the requirement "No triple characters" turns to green as if it was okay. Then, erasing the written password will turn the other two options to red, leaving "No triple characters" in green. 

Pre-Conditions:
Having Safe Wallet with no information, as if it was the first opening,

Steps to reproduce:
1. Enter the Safe Wallet App for iOS
2. Tap on "Setup Password"
3. Advance until password creation 
4. Write a password with more than 8 characters. repeating a character at least three times, then erase all
5. Observe

Expected result: 
"No triple character" requirement should go red when typing the password, and remain red when erased.

Actual result:
"No triple character" requirement goes green and so it remains when the password is erased.

Smartphone:
I-phone 7/X - iOS 12.1

Note: 
The password used for this test is _Saladsoysing1090_

![img_20181106_130554221](https://user-images.githubusercontent.com/44405181/48077099-62f79600-e1c5-11e8-96e0-0ed0d2bbf274.jpg)

![img_20181106_130546283](https://user-images.githubusercontent.com/44405181/48077138-77d42980-e1c5-11e8-8b60-bb04a509786b.jpg)

**Comment by sche** [comment]
Thanks for the report. The message is misleading. It means no triple chars in a row. We will improve that! 👍
