### ISSUE TITLE
When sending, point and comma discrepancy in displayed balance and send field

### ISSUE THREAD

**Issue by Mettenim** [gnosis/safe-ios-legacy#385]
**Describe the bug**
When sending Eth, the app displays a balance using a point for decimals. But in the field for entering funds to send, it requires a comma (but shows point). 

**To Reproduce**
1. Go to 'overview screen'
2. Click on 'Eth'
3. Enter amount to send, ie. 001
5. Error shows until user enters a comma, ie. ,001. (But when entering a comma, a point is displayed.)

**Expected behavior**
User should be able to enter a point, and a point should be showed for entering decimals. (American system)

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - App Version [current, as of 19 Nov]

**Comment by DmitryBespalov** [comment]
I assume that "requires a comma" is the placeholder text that you see (`0,00`). This was not localized, adding now.
