### ISSUE TITLE
Design review

### ISSUE THREAD

**Issue by Mettenim** [gnosis/safe-ios-legacy#425]
**General UI adjustments:
- Decrease radius of shadow on identicon.

**Comment by Mettenim** [comment]
On Asset overview screen: Display the "(+) Add" component at the bottom of the list.

**Comment by Mettenim** [comment]
Onboarding- first deposit currently displays the alert:  "Insufficient funds". Please change to "Make your first deposit screen."

**Comment by DmitryBespalov** [comment]
will be handled in other tasks
