### ISSUE TITLE
Next button sends you to previous stage

### ISSUE THREAD

**Issue by damiandragobetzky** [gnosis/safe-ios-legacy#431]
User won't be able to write recovery phrase because he's sent to previous screen.

Pre-conditions:
First time user login

Steps to reproduce: 
1- Tap on "Create a new Safe"
2- Tap on "Next"
3- Tap on "Recovery phrase"
4- Tap on "Next" 
5- Observe

Expected result: 
User should be sent to the next stage in order to write the Recovery phrase.

Actual result:
User is sent back to the previous screen. 

Environment: 
iPhone X - iOS v12.1 
Testflight Rinkeby - v2.1.5(3) 

https://drive.google.com/open?id=1fsIgm8KU6AR8O091_W2gHW1HkD-crUkV

**Comment by DmitryBespalov** [comment]
Hi @damiandragobetzky could you please clarify the app version in TestFlight? 
Currently, the latest released version is 0.9.0, but you have specified 2.1.5 (3), which I'm not aware of.

**Comment by DmitryBespalov** [comment]
Ok, I got what you're referring to. This is a UX issue. Happens when you already set up the mnemonic and then open the recovery phrase again.

**Comment by MicaelaPesado** [comment]
Hi @DmitryBespalov sorry for not answering before. Yes, that´s what we are refferring to.

**Comment by DmitryBespalov** [comment]
All right, this is postponed because the UX for the onboarding is going to be changed anyway.

**Comment by DmitryBespalov** [comment]
@tschubotz this is request for change in requirements

**Comment by tschubotz** [comment]
That's intended behavior, albeit bad UX imo. We will adapt this flow anyway to use a similar one like on Android.

**Comment by DmitryBespalov** [comment]
This will be changed when iOS and Android designs aligned.
