### ISSUE TITLE
Dot doesn´t work 

### ISSUE THREAD

**Issue by MicaelaPesado** [gnosis/safe-ios-legacy#437]
When trying to send ETH, the dot doesn´t work.

**To Reproduce**

1. Go to the Safe app download by testflight
2. Click on send.
3. Try to introduce an amount with a dot.
4. Observe.

**Expected behavior**
The dot works well, and the amount can be correctly introduce.

**Actual behavior**
The dot doesn´t work.

**Screenshots**
https://drive.google.com/open?id=10fRLH--dMsCzoX9JRRGUKgjLT8VZvY1c

**Smartphone (please complete the following information):**
 - Device:  iPhone 7
 - iOS Version: 12.1.1
**Additional context**
- App downloaded via: https://testflight.apple.com/join/fMCYpOfT 
- Production envs
@rmeissner @tschubotz

**Comment by DmitryBespalov** [comment]
@MicaelaPesado Thank you for reporting! I need more information about your phone:

Could you please make a screenshot from Settings -> General -> Language & Region?

**Comment by MicaelaPesado** [comment]
Here it is! It´s the iPhone 7 not the X.
![img_1065 1](https://user-images.githubusercontent.com/44403034/49594451-abd17480-f954-11e8-9ad2-69a1caac69d6.PNG)

**Comment by DmitryBespalov** [comment]
This was hard to trace.
For some reason, not known to me, sometimes iPhone shows dot "." instead of "," even though regional settings show comma "," (happens when multiple languages in the list and some of them use dots)... 
In the end, I made the app accept any decimal separator - comma or point
