### ISSUE TITLE
Resync with browser extension

### ISSUE THREAD

**Issue by germartinez** [gnosis/safe-ios-legacy#450]
It would be nice having a "resync with the extension" option in the menu of the app that sends the payload with the type "safeCreation" to the extension (like during the pairing process). This would be very useful in case the extension doesn't receive the "safeCreation" push notification or the Safe is deleted on the extension side.

**Comment by sche** [comment]
I would not hurry with this feature. 
1) It should be a very rear case when we could need it. --> Does it make sense to allocate space in the menu for that?
2) Are we going to use "pull strategy" for info sync with help of our services? @tschubotz
