### ISSUE TITLE
Crash when scanning QR code

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-ios-legacy#462]
**Describe the bug**
When I'm scanning a QR code in a specific way, the app crashes

**To Reproduce**
1. Setup a new Safe (That's what I did, not sure if it's necessary.
2. Tap ETH
3. Tap the address field
4. Select "Scan QR code"
5. DON'T scan, just close the camera
6. Now enter an amount (I took 0.001 ETH)
7. Tap the address field again
8. Select "Scan QR code"
9. 💥 💥 💥 💥 

**Expected behavior**
No crash :)

**Screenshots**
-

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - iOS Version: Not sure, can check if important.
 - App Version: 0.9.1 (Rinkeby, via Testflight)

**Additional context**
-

**Comment by DmitryBespalov** [comment]
Please test using 0.10.0 version.

**Comment by tschubotz** [comment]
seems to be fixed in 0.10.0
