### ISSUE TITLE
Some custom tokens bug/issues

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-ios-legacy#464]
**Describe the bug**
Some things look odd when managing tokens

**To Reproduce**
1. Open app
2. Tap manage tokens

**Expected behavior**
(1) The token RLOVE was auto enabled after creating a Safe. Isn't this a Rinkeby token?

(2) The first token in the list is (TTC)(TTC) (TTCProtocol). This format looks odd (cf screenshot). Is this intended?

(3) Quite some token miss a symbol, like ABT, AGI, AMB. Is this intended?

**Screenshots**
![img_70ccc3b5d550-1](https://user-images.githubusercontent.com/1380529/50011285-f76ec880-ffbb-11e8-85b2-8fd85d8901ff.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - iOS Version: ?
 - App Version: 0.10.0

**Additional context**
-

**Comment by DmitryBespalov** [comment]
@tschubotz This is the default output taken from our token service. In it, many tokens are missing icons.

Which tokens would you like to be enabled? 

I'll refresh this data with current output of token service

**Comment by DmitryBespalov** [comment]
the server data is currently not correct, waiting for updates.

**Comment by tschubotz** [comment]
Okay, @Uxio0 knows about it or who can make sure that the data is correct?

**Comment by DmitryBespalov** [comment]
I'll wait for Uxio's update - he's changing logo URLs at the moment, so the new data is not valid right now.

The app's data is updated from my gist, and it doesn't need re-submitting the app.

**Comment by tschubotz** [comment]
ah okay. Why is a different gist than the one from @rmeissner ? (which we use on Android afaik)

**Comment by Uxio0** [comment]
@tschubotz @DmitryBespalov I have just updated the logos. I'm using the same script that @rmeissner is using and pointing the logos to his repo until we set them up on S3. I don't know how to check if data is ok, I'm trusting etherscan tokens page: https://etherscan.io/tokens

**Comment by DmitryBespalov** [comment]
ok, I'll check it out

**Comment by DmitryBespalov** [comment]
Ok, I will update the configuration in the new build. The only thing to keep in mind, the update of tokens doesn't happen immediately and sometimes there are weird states - some tokens updated, some not. Eventually, all are updated to new token versions, but it takes 1-2 app restarts. At this point, figuring out all the bug cases and fixing it is not feasible. I'll keep this open until I get new build.

**Comment by tschubotz** [comment]
Thanks for fixing it. I still see the Love token on mainnet as discussed though.
