### ISSUE TITLE
Scanning of QR code with non-checksummed address fails silently

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-ios-legacy#466]
**Describe the bug**
No feedback when scanning an address qr code.

**To Reproduce**
1. Go to Safe overview
2. Select ETH
3. Scan QR code with non-checksummed address
-> Nothings

**Expected behavior**
The app would tell me why it's not working. e.g. even something like "Invalid address" would work.

**Screenshots**
-

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - iOS Version: iOS 12.1.1
 - App Version: 0.10.0

**Additional context**
-

**Comment by DmitryBespalov** [comment]
@tschubotz could you please post the QR code

**Comment by tschubotz** [comment]
I used a wrong QR code. Seems to work with non-checksummed addresses after all. My bad.
