### ISSUE TITLE
Rejection of browser extension not reflected in app UI

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-ios-legacy#467]
**Describe the bug**
When I reject a tx with my browser extension I don't see this in my mobile app

**To Reproduce**
1. Try to send ETH to someone
2. On the Chrome extension popup, click "reject"
-> Nothing happens inside the app

**Expected behavior**
I expect to have a visual indication that something failed: https://zpl.io/b6jZKYR

**Screenshots**
-

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - iOS Version: iOS 12.1.1
 - App Version: 0.10.0

**Additional context**
-

**Comment by DmitryBespalov** [comment]
Hi, I need more information. What screen do you see? Could you please post a screenshot or description?

Also, how often is this reproducible?

**Comment by DmitryBespalov** [comment]
Could you check if you actually receive the push notification?

1) try to send ETH - continue
2) lock your phone
3) reject from the extension

see if you've got a push notificaiton

**Comment by tschubotz** [comment]
I stayed on the same screen, i.e. the screen where there is the progress bar "awaiting confirmation"
![img_aa5108c8849b-1](https://user-images.githubusercontent.com/1380529/50099362-37cd8100-021e-11e9-9981-a7dd05d2b509.jpeg)

**Comment by tschubotz** [comment]
On Friday, it failed everytime. Today, it doesn't anymore.

The only scenario where I still don't see an updated UI is the following:

1. Send ETH (i.e. enter a recipient and an amount)
2. Continue
3. Confirm with Chrome extension
-> UI updates
4. Don't submit, but go back
5. Continue again
6. Reject with Chrome extension
-> UI doesn't update anymore. It stays in the awating confirmation step. (I do get teh push, i.e. when I lock the phone in between I see the puhs. But when opening the push, I don't see an updated UI)

**Comment by DmitryBespalov** [comment]
That is very helpful, thank you.

**Comment by tschubotz** [comment]
works now for me
