### ISSUE TITLE
Rejected tx from browser extension shows up in tx list

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-ios-legacy#469]
**Describe the bug**
Rejected tx from browser extension shows up in tx list

**To Reproduce**
I have a mainnet Safe with DAI.
1. On Safe overview, tap on DAI
2. Scan QR code for recipient address
3. Enter DAI amount
4. Next
5. On the Screen where you wait for the confirmation, go back
6. Back to the Safe overview
7. Now reject tx with browser extension
8. Open tx list
-> I see the rejected tx.

(Side note, when now opening that tx and clicking the etherscan link the app crashes.)

**Expected behavior**
I expect to see nothing since the tx list should just show transactions that have been confirmed by all owners, i.e. only txs that have an etherscan link with a tx hash.

**Screenshots**
-

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - iOS Version: 12.1.1
 - App Version: 0.10.0

**Additional context**
-

**Comment by DmitryBespalov** [comment]
Hello, this is a change in the requirements from the current implementation.

Nevertheless, this is easy to change.

**Comment by tschubotz** [comment]
Thank you Dima
