### ISSUE TITLE
Browser extension rejection opens dead-end tx screen.

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-ios-legacy#470]
**Describe the bug**
Browser extension rejection opens dead-end tx screen were I cannot do anything.

**To Reproduce**
1. Select an asset (I used DAI)
2. Enter recipient
3. Enter amount
4. Hit next
5. Go back to the Safe overview screen
6. Tap the tx list tab
7. Now reject with the browser extension
-> iOS app opens a screen automatically where I cannot do anything.

**Expected behavior**
That screen just doesn't open at all.

**Screenshots**
![img_b34ed0ea60fe-1](https://user-images.githubusercontent.com/1380529/50081175-1ce31880-01ee-11e9-8c95-b1b903798a1f.jpeg)

**Smartphone (please complete the following information):**
 - Device: SE
 - iOS Version: 12.1.1
 - App Version: 0.10.0

**Additional context**
-

**Comment by DmitryBespalov** [comment]
this is bug in specs, changing the behavior now

**Comment by tschubotz** [comment]
Sorry for the specs confusion. Thank you for adapting it.
