### ISSUE TITLE
QR scan doesn´t show any message when you scan a code which isn´t the expected

### ISSUE THREAD

**Issue by MicaelaPesado** [gnosis/safe-ios-legacy#475]
QR scan doesn´t show any message when you scan a code which isn´t the expected

1. Set up a new safe
2. Tap on scan QR code from browser extension.
3. Scan a code from another wallet extension 
4. Observe

**Expected behavior**
The app shows a pop up message which tells the user that this QR is incorrect.

**Actual behavior**
The app tries to scan the code and doesn´t show any message.

**Smartphone:**
 - Device: iPhone X
 - iOS Version: 12.1
 - App Version: Gnosis Safe Mainnet 0.10.0

**Comment by DmitryBespalov** [comment]
Please attach QR code example

**Comment by DmitryBespalov** [comment]
@tschubotz spec bug

**Comment by MicaelaPesado** [comment]
Hi @DmitryBespalov I mean any tipe of QR code which is not the one to connect with the browser extension. 
Here it´s an example: 
![image](https://user-images.githubusercontent.com/44403034/50286390-f87d7b00-043d-11e9-9114-9c1c26aae7a8.png)

**Comment by DmitryBespalov** [comment]
will be changed as part of the redesign.
