### ISSUE TITLE
"Make a copy" button works silently

### ISSUE THREAD

**Issue by damiandragobetzky** [gnosis/safe-ios-legacy#486]
When copying the recovery phrase to the clipboard, the "Make a copy" button won't show a message letting the user know the phrase's been copied.

Steps to reproduce: 
1- Create new Safe
2- Tap on "Recovery phrase"
3- Tap on"Make a copy"
4- Observe

Expected result: 
When copied, the app should show a message letting the user know it.

Actual result:
The phrase gets copied but the user won't know it unless he pastes it.

Environment: 
Safe app - v0.10.0 (2)
iOS - v11.4.1
iPhone 5

**Comment by DmitryBespalov** [comment]
@tschubotz spec bug

**Comment by DmitryBespalov** [comment]
Hi, this will be handled as part of upcoming redesign to align iOS and Android UI/UX
