### ISSUE TITLE
Loading icon gets stuck

### ISSUE THREAD

**Issue by MicaelaPesado** [gnosis/safe-ios-legacy#494]
**Describe the bug**
When refreshing the list of assets the loading icon gets stuck. 

**To Reproduce**
1. Go to the main page.
2. Drag down the token list.
3. Tap on transactions while refreshing.
4. Go back to assets.
5. Observe.

**Expected behavior**
The token list refreshes and the loading icon goes away.

**Actual behavior**
Loading icon gets stuck.

**Smartphone (please complete the following information):**
 - Device:  iPhone X
 - iOS Version:  iOS 12.1
 - App Version: 0.10.0 (2)

https://drive.google.com/open?id=1lwE5ixRH5kZN-IYIudf2oEO1gXd5veDW

**Comment by sche** [comment]
Can not reproduce. @MicaelaPesado is it reproduced on your phone on the latest build?

**Comment by MicaelaPesado** [comment]
It works well in the version 1.1.0 (138) downloaded via Crashlitycs.
