### ISSUE TITLE
Add browser extension later

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-ios-legacy#497]
# Story
As a user I am able to add a browser extension to my Safe that didn't have one connected previously in order to secure it.

# Background
The Android app has that feature already. We left it out for the first iOS version but should add it soon.

# Acceptance criteria
- User needs to scan QR code of new Chrome extension: https://zpl.io/V1z96rJ
- User needs to transfer more ETH, if funds are insufficient: https://zpl.io/a75QRmp
- User needs to review and submit the transaction: https://zpl.io/VOKAq4r
- User ends up on the transaction list, seeing their transaction in progress

The flow is similar to #496

**Comment by DmitryBespalov** [comment]
@tschubotz can this be closed? I'll reopen / recreate when gnosis/safe#73 will move to dev backlog

**Comment by tschubotz** [comment]
Yes
