### ISSUE TITLE
Change password

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-ios-legacy#498]
# Story
As a user I am able to change the device password in my Safe app in order to adapt if exposed.

# Background
The Android app has that feature already. We left it out for the first iOS version but should add it soon.

# Acceptance criteria
- User is able to start the flow from the settings menu.
- User needs to enter current password first: https://zpl.io/VYGoNDn
  - Incorrect password: zpl.io/aRWGDAe
  - Validation should happen only when tapping "next"
- User needs to enter & confirm a new password: https://zpl.io/a75Q6kv
  - Validation automatically when entering the new password & also when confirming.
  - Incorrect password criteria or pw doesn't match: https://zpl.io/VOKAjjL
- New password is set upon tapping "Save" or "Go" on the keyboard.
- If the flow is canceled before the final step, the old password remains set.

**Comment by DmitryBespalov** [comment]
@tschubotz can we close it and reopen when specs ready?

**Comment by tschubotz** [comment]
Sure, this is from before we started wit hthe new spec process.
