### ISSUE TITLE
Transaction without extension fails

### ISSUE THREAD

**Issue by MicaelaPesado** [gnosis/safe-ios-legacy#500]
**Describe the bug**
Transactions can´t be submited without the browser extension connected.

**To Reproduce**
1. Create a new safe without the browser extension connected.
2. Tap on send Ether.
3. Complete the recipient address and an amount to send.
4. Observe

Expected result:
The transaction is successfully made.

Actual result:
The transaction fails, and when trying to submit the same transaction, the app crashes. 

**Smartphone (please complete the following information):**
 - Device:  iPhone X
 - iOS Version:  iOS 12.1
 - App Version 0.10 (2)

https://drive.google.com/open?id=1O7H-Q2I6ksXha6Yvx49yTDAPG6n3XlwR

**Comment by DmitryBespalov** [comment]
I could reproduce under 100% network loss conditions (request time out) + submitting the transaction again.

**Comment by DmitryBespalov** [comment]
Update on this. 

I tracked down the possible causes of the crash and so far I could find two different causes of this behavior. One is related to network conditions, and the second is related to transaction status synchronization and database access. Both of them hint on the flaws in the current feature specification, and subsequently in the code design.

Note, there might be other causes that I haven't found yet, but I expect these two to be all.

## Plan for the solution

1. Re-estimate the probability of experiencing both causes in the production
2. Consider alternative solutions for both causes
3. Prepare automated tests that reproduce the problems
4. Solve the problems
5. Verify the solutions
6. Submit the fixes as a hotfix release to the App Store.

**Comment by MicaelaPesado** [comment]
Hi @DmitryBespalov we are re-testing it and we still can't make a transaction without the browser, but now we have a different issue. Here it´s a link to a video for you to see it.

https://drive.google.com/open?id=1xnXSn58F8MyyhONIYTLDxfKj9jkao5GN

**Comment by DmitryBespalov** [comment]
Seems related to the first issue. The main thing is the network errors...

**Comment by MicaelaPesado** [comment]
It can't be reproduced in the new version:  Gnosis Safe - Rinkeby 1.0.1

**Comment by DmitryBespalov** [comment]
thank you
