### ISSUE TITLE
Safe recovery fails due to "Server Error"

### ISSUE THREAD

**Issue by damiandragobetzky** [gnosis/safe-ios-legacy#501]
Description:
When you recover your safe but skip connection with extension, a pop-up appears showing the message "Failed to recover because of internal server error". 

Steps to reproduce:
1-Recover Safe
2-Write recovery phrase and continue
3-Skip connection with extension
4-Observe 

Expected result:
The Safe is recovered.

Actual result:
A pop-up appears showing the message "Failed to recover because of internal server error".

Smartphone:
Device: iPhone X
iOS Version: iOS 12.1
App Version 0.10 (2)

Capture: 
https://drive.google.com/drive/folders/12OO4az6cIB9F8FW1pomo8Yy9SuXQrOk4?ogsrc=32

**Comment by DmitryBespalov** [comment]
Hi @damiandragobetzky! Thank you for the submission. I need some more information before I can proceed.

I've seen the safe address in the video, but could you please provide the safe address here? Also, where have you downloaded the app to test - was it TestFlight or Fabric?

**Comment by damiandragobetzky** [comment]
Hi @DmitryBespalov ! Yes, I'm sorry I forgot: We used (And always use) TestFlight. 
As to the address, I'm leaving it here along with the phrase:

0xDc8E8BE51C9b1D6bbfd6625C987B114C31a1bcDd
Pet risk major crucial tide pottery shoulder second august salon price fun

**Comment by DmitryBespalov** [comment]
thank you, I'll take a closer look.

**Comment by MicaelaPesado** [comment]
Now it's working! Aaccording to @Uxio0  it was a problem with the node that was updated today.

**Comment by DmitryBespalov** [comment]
I'm closing this now
