### ISSUE TITLE
Amount of DAI token not displayed correctly

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-ios-legacy#506]
_Bug reported by @bh2smith_

**Describe the bug**
Ben has a Safe, owns DAI, but sees a balance of 0 😱 

**To Reproduce**
- Have a mainnet Safe.
- Enable DAI (Token icon is missing, too)
- Go to token overview screen
-> Nothing 😢 

**Expected behavior**
- The full amount is displayed (like on Etherscan)

**Screenshots**
- 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 7]
 - iOS Version: [e.g. iOS 12.1.2]
 - App Version: Mainnet release from today.

Ben can give more insights if this is really necessary.

**Additional context**
- Gnosis Safe Rules!

**Comment by bh2smith** [comment]
All fixed now! Thanks fellas
