### ISSUE TITLE
ErrorHandler.swift line 36

### ISSUE THREAD

**Issue by gnosis-safe-ios-crashlytics** [gnosis/safe-ios-legacy#515]
#### in closure #1 in static ErrorHandler.showFatalError(message:log:error:file:line:)

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/gnosis/ios/apps/io.gnosis.safe.prerelease/issues/5c49bcc2f8b88c29635cd82f?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/gnosis/ios/apps/io.gnosis.safe.prerelease/issues/5c49bcc2f8b88c29635cd82f?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by DmitryBespalov** [comment]
Reproduced when trying to set up a password with more than 100 characters length.

**Comment by DmitryBespalov** [comment]
Will remove this requirement.

**Comment by DmitryBespalov** [comment]
fixed
