### ISSUE TITLE
Extra space in the text during password setup

### ISSUE THREAD

**Issue by KristinaMayman** [gnosis/safe-ios-legacy#519]
**Describe the bug**
In the text that appears during the password setup, there is an extra space between "usage" and "data" in the phrase "We collect anonymized app usage data and crash reports to ensure quality of our app."

**To Reproduce**
1. Go to the Safe app
2. Click on 'Setup password'
3. See error

**Expected behavior**
There should be one space.

**Smartphone**
 - Device: iPhone 7
 - iOS Version: iOS 12.1.2
 - App Version: 1.0.1 (2)

**Comment by DmitryBespalov** [comment]
Thank you, will fix.
