### ISSUE TITLE
Giving the user a chance to setup the browser extension after the mobile app setup.

### ISSUE THREAD

**Issue by cryptoeraser** [gnosis/safe-ios-legacy#521]
**Is your feature request related to a problem? Please describe.**
Yes. I have installed the iOS app last night. And I did not have chrome open. So I skipped the browser-extension setup stage. Later, after setting up my GnosisSafe wallet, I realized that there is a need for the browser-extension. However, I was not able to go back to that menu option and input the QR code from my browser-extension.

**Describe the solution you'd like**
I wanted to go back to the browser-extension setup page so I can setup the chrome extension. Could you please implement this? If possible?

**Describe alternatives you've considered**
The only way to solve the problem was to remove the app, re-install and then get into the browser-extension setup stage, where I was able to read the QR code and link the mobile app to the chrome extension.

**Additional context**
Removing and recovering the wallet, only and only to be able to link to the browser-extension was not a very friendly UX moment. Unless I did something wrong? Is there a way to avoid removing and recovering the wallet only to be able to link to the browser-extension?

It cost me a bit of ETH when I removed and re-installed the app :P

**Comment by DmitryBespalov** [comment]
Hi @cryptoeraser, thank you for your request. We have this feature on our list for the next planned release.

(duplicate #497)

**Comment by cryptoeraser** [comment]
Thanks. Does that also mean that, once I have the iOS app setup once on my device, and my browser-extension linked to it at home, on my home computer, I cannot effectively install the browser-extension at my work computer and enable the wallet there as well? Is that the case?

Cause now, at my work computer, I have set up the browser-extension and now it asks me to scan the QR code so I can activate my GnosisSafe wallet, but there is not option in my iOS GnosisSafe app to receive that QR code?

Any advice? Thanks.

**Comment by cryptoeraser** [comment]
Ok. I did a bit of digging in the issues section: it seems like that is the issue until this functionality is implemented. Thanks.

**Comment by DmitryBespalov** [comment]
> I cannot effectively install the browser-extension at my work computer and enable the wallet there as well? Is that the case?

Yes, that is the case. At the moment the app supports only one extension.

> there is not option in my iOS GnosisSafe app to receive that QR code?

Currently, the app does not support connecting additional extension or connecting an extension after the safe was created.

**Comment by DmitryBespalov** [comment]
closing as duplicate
