### ISSUE TITLE
"Transaction Fee [?]" bugs the app

### ISSUE THREAD

**Issue by damiandragobetzky** [gnosis/safe-ios-legacy#525]
Description:
when starting a transaction, clicking the [?] next to "Transaction Fee", minimizing the app and re-entering the password, makes the screen go black.

Steps to reproduce:
1-Start a transaction 
2-Open the [?] next to "Transaction Fee"
3-Minimize the app for 60 seconds
4-Re-open the app
5-Write password 
6-Observe

Expected result:
The app remains the way it was before minimizing it.

Actual result:
The screen went all black, with nothing but the Transaction Fee pop-up 

Smartphone:
Device: iPhone X
iOS Version: iOS 12.1
App Version 1.0.1(2)

Capture:
https://drive.google.com/open?id=1HD65zxfAz1qeZYCkCAXsTcpGS46vVj78

**Comment by MicaelaPesado** [comment]
Hi @DmitryBespalov ! It also occurs when you: 
1. Tap on the identicon on the main page.
2. Tap on the share address icon.
3. Minimize the app for 60 seconds
4. Re-open the app
5. Write password

**Comment by MicaelaPesado** [comment]
It's still happening on the new version: Gnosis Safe - Rinkeby 1.0.1

**Comment by DmitryBespalov** [comment]
yes, this was not fixed.
