### ISSUE TITLE
Use correct color scheme for app icon

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-ios-legacy#546]
It is expected that the app icons correspond to the icons on https://sites.google.com/gnosis.pm/safe/developer?authuser=1

This is not the case for Rinkeby - Staging

**Comment by sche** [comment]
@posthnikova do we have somewhere proper icons for iOS Dev (red) and Staging (yellow) in all required resolutions?

**Comment by posthnikova** [comment]
I don't have ready app icons, just vector icons. I have to generate all resolutions

**Comment by posthnikova** [comment]
[rinkeby.zip](https://github.com/gnosis/safe-ios/files/2951620/rinkeby.zip)

@sche Here are the icons

**Comment by sche** [comment]
thank you @posthnikova
