### ISSUE TITLE
bootstrap.sh script has syntax error

### ISSUE THREAD

**Issue by valeriyvan** [gnosis/safe-ios-legacy#552]
**Describe the bug**
bootstrap.sh script has syntax error

**To Reproduce**
1. run `scripts/bootstrap.sh` in terminal

**Expected behavior**
I expect script run and bootstrap project.

**Screenshots**
script fails with syntax error:
```
Installing git configuration
~/Documents/safe-ios/.git/hooks ~/Documents/safe-ios
scripts/bootstrap.sh: line 57: syntax error near unexpected token `fi'
```

**Smartphone (please complete the following information):**
 - Device: not relevant to issue
 - iOS Version: not relevant to issue
 - App Version not relevant to issue

**Additional context**
n/a

**Comment by DmitryBespalov** [comment]
thank you for the fix!
