### ISSUE TITLE
Potential problem with sqlite wrapper

### ISSUE THREAD

**Issue by valeriyvan** [gnosis/safe-ios-legacy#558]
**Describe the bug**
```
    public var findFirstSQL: String {
        return "SELECT \(fieldNameList) FROM \(tableName) LIMIT 1;"
    }
```
Are you aware that repeating this call might give different data?
If there's no ordering, select returns whatever engine has in memory from previous requests. It might return last record if last record is already happen to be buffered.
Otherwise `findFirstSQL` doesn't communicate what it is doing.

**To Reproduce**
not relevant

**Expected behavior**
not relevant

**Screenshots**
not relevant

**Smartphone (please complete the following information):**
 - Device: not relevant
 - iOS Version: not relevant
 - App Version not relevant

**Additional context**
not relevant

**Comment by DmitryBespalov** [comment]
This is a mistake. You are right, from the SQLite docs:


> If a SELECT statement that returns more than one row does not have an ORDER BY clause, the order in which the rows are returned is undefined

**Comment by valeriyvan** [comment]
Do you agree it's a bug?

**Comment by DmitryBespalov** [comment]
Yes and no. Yes, because the order is undefined, and it's better to define it (imo by primary key column). No, because this findFirst was supposed (and so far used) only when the table contains only a single row. Adding the ORDER BY would help find issues with the logic if there are any.

**Comment by valeriyvan** [comment]
Ok
