### ISSUE TITLE
Building the app for the first time

### ISSUE THREAD

**Issue by ricburton** [gnosis/safe-ios-legacy#570]
Here are the errors I ran into. Keen to check out the project on my machine.
<img width="2032" alt="screenshot 2019-02-24 at 18 16 50" src="https://user-images.githubusercontent.com/438160/53306926-14980100-3861-11e9-9093-6902f4b0bd54.png">
<img width="2032" alt="screenshot 2019-02-24 at 18 16 27" src="https://user-images.githubusercontent.com/438160/53306927-1661c480-3861-11e9-8ddd-47cc772cbaf0.png">

**Comment by DmitryBespalov** [comment]
Hi @ricburton, what were the steps you did?
