### ISSUE TITLE
force unwrap `address!` of wallet instance appears 40 times

### ISSUE THREAD

**Issue by valeriyvan** [gnosis/safe-ios-legacy#606]
Something is wrong with this property. Isn't it a sign of design flaw? At least it should be implicitly unwrapped optional or it shouldn't be an optional at all.

**Describe the bug**
not relevant

**To Reproduce**
not relevant

**Expected behavior**
not relevant

**Screenshots**
not relevant

**Smartphone (please complete the following information):**
 - Device: not relevant
 - iOS Version: not relevant
 - App Version not relevant

**Additional context**
not relevant

**Comment by DmitryBespalov** [comment]
Make the `address: Address!` and only use optional unwrapping where it is used now.
