### ISSUE TITLE
Address highlighting is a little bit off 

### ISSUE THREAD

**Issue by mmv08** [gnosis/safe-ios-legacy#613]
**Describe the bug**
Address highlighting seems a little bit off to me. It highlights only the middle of the address but I think the desired behavior was highlighting whole address

**To Reproduce**
1. Go to Menu
2. Expand the address section
3. See error

**Expected behavior**
Whole address string is highlighted (or not highlighted)

**Screenshots**
![image](https://user-images.githubusercontent.com/16622558/54124495-ff53d280-441b-11e9-8922-8fa9a3d78b03.png)

**Smartphone (please complete the following information):**
 - Device: iPhone XS
 - iOS Version: iOS 12.1.4
 - App Version: 1.0.1

**Additional context**
Also If I remember correctly the same problem appears on window where it asks you to deposit ETH to create the safe

Also I really wanted to click on address to copy it but it had not such functionality :(
I kinda got confused because the color made me think that this is not just a regular text and I could click to copy it
(yes I know that there's "Share" button :slightly_smiling_face: )

**Comment by DmitryBespalov** [comment]
Hi there, we are reworking the address label. The coloring that you mentioned is intended - to highlight the first and last characters of the address. 

The copy functionality will be added as part of another ticket.
