### ISSUE TITLE
1Password button

### ISSUE THREAD

**Issue by ricburton** [gnosis/safe-ios-legacy#630]
**Is your feature request related to a problem? Please describe.**
I store my Gnosis Safe password in 1Password. I would like to make it easier to paste it in. 

**Describe the solution you'd like**
https://github.com/agilebits/onepassword-app-extension

**Describe alternatives you've considered**
The Passwords tab in iOS12

**Comment by tschubotz** [comment]
Issue moved to [gnosis/safe #204](https://github.com/gnosis/safe/issues/204) via [**ZenHub**](https://www.zenhub.com/)

**Comment by tschubotz** [comment]
Issue moved to [gnosis/safe #205](https://github.com/gnosis/safe/issues/205) via [**ZenHub**](https://www.zenhub.com/)
