### ISSUE TITLE
Visual Feedback on "Make a copy" button

### ISSUE THREAD

**Issue by ricburton** [gnosis/safe-ios-legacy#631]
**Is your feature request related to a problem? Please describe.**
I wasn't sure if it had been copied.

**Describe the solution you'd like**
Visual (and haptic) feedback when I tap the button

**Comment by valeriyvan** [comment]
Wanted to open same issue. 
You don't understand if "Make a copy" works until you try to paste phrase somewhere (1Password).

**Comment by MicaelaPesado** [comment]
It's still happenning in the version 1.1.0 (138)
