### ISSUE TITLE
Stuck during Safe creation, unable to restore.

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-ios-legacy#632]
**Describe the bug**
Chris was creating a Safe. The app was stuck on the creation screen even though the Safe was created on the blockchain.
After reinstalling the app and trying to restore, the app said: "not a valid Safe mnemonic".

**To Reproduce**
?

**Additional info:**
- Safe: https://etherscan.io/address/0x79b9B29Bd64983ccF46aA2Fc6c8cc8f054F08Bcd
- Owner addresss derived from mnemonic: 
  - 0x9884aA51B9fCf3240c0360F029a07E6eBEE507a7
  - 0x8f6F2Fcd8B2218737058ABf6B43281abF384AAdF
  - I can share the mnemonic via another channel if that's needed
- The 2 owner addresses above don't match with the owner addresses on the blockchain. So something odd is happening.

**Comment by DmitryBespalov** [comment]
@tschubotz 
Thanks to @Uxio0, we know the actual safe address `0xFc6E482D11E5d38a2F74f2E48E948Da289f0E0eE`. We re-triggered deployment and the safe is deployed now and can be restored if needed.

We will continue observing such errors when safe deployment is stuck to find out the root cause.
