### ISSUE TITLE
Small UI bug: Password field skewed on small device

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-ios-legacy#651]
**Describe the bug**

**To Reproduce**
- Just cold start the app on e.g. an iPhone SE

**Expected behavior**
- Input field remains the same, no skewing

**Screenshots**
<table>
<tr>
<td>Not skewed:</td> 
<td>Skewed:</td>
</tr>
<tr>
<td>

![IMG_5605](https://user-images.githubusercontent.com/1380529/55328719-4d914a00-548d-11e9-8313-b7e7f0ebede8.png)

</td>
<td>

![IMG_5604](https://user-images.githubusercontent.com/1380529/55328724-4ff3a400-548d-11e9-8b51-d5541eaac05b.png)

</td>
</tr>
</table>

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - iOS Version: iOS 12.2
 - App Version 1.1.0

**Comment by DmitryBespalov** [comment]
Cannot reproduce on the simulator for the current development version
