### ISSUE TITLE
Adjust address input component

### ISSUE THREAD

**Issue by sche** [gnosis/safe-ios-legacy#659]
After discussing with @posthnikova 

Open question:
- Leave left icon or not? If yes, the new icon will be provided.

Changes needed:
- Address label font size should be 16
- Address label font should shrink in size for a small screen (iPhone SE)
- Address input component should be higher with an address in place

**Comment by lukasschor** [comment]
@posthnikova @sche I would be in favor for keeping the icon in the recipient field. What would be the reasons for removing it?

**Comment by posthnikova** [comment]
@lukasschor 
- It looks cleaner without it
- One icon hardly represents the variety of addresses, these could be people, organisations, smart contracts

**Comment by lukasschor** [comment]
I can see your point. I put it on the agenda for tomorrows UX sync. Let's discuss and decide there. :)

**Comment by sche** [comment]
@lukasschor @posthnikova so what was the result of the discussion? Should we remove the icon?

**Comment by lukasschor** [comment]
Yes, remove the icon
