### ISSUE TITLE
Change password: Incorrect password message isn't shown  

### ISSUE THREAD

**Issue by MicaelaPesado** [gnosis/safe-ios-legacy#678]
**Incorrect password message isn't shown  in the Change password section, when entering the current password**

**Steps to reproduce:**
1. Go to Safe ios app
2. Tap on Menu
3. Tap on  "Change Password"
4. Enter an incorrect password.
5. Observe
**Expected behavior**
An "incorrect password message" is shown and the user isn't able to tap on the next button.
![image](https://user-images.githubusercontent.com/44403034/56137319-f0a49200-5f6a-11e9-9d18-77b60819701b.png)

**Actual behavior**
The user is able to tap on "next" but the screen shakes and the user can't continue.
https://drive.google.com/open?id=10vPQnwF1Kkw_Efh9n6Hz4K_Yuwv9757g

**Smartphone:**
 - Device: iPhone 7
 - iOS Version: iOS 12.1
 - App Version: 1.1.0 (138) via Crashlytics

**Comment by sche** [comment]
I discussed with @posthnikova how it should look like.
*Current behavior*: the input shakes if the password is wrong, and after 3 unsuccessful attempts, it shows a blocking timer.
*Future behavior* 
- The input becomes red and shows an error on the unsuccessful attempt (only when pressing next/return buttons). 
- It stays red when a user continues typing. 
- If the field cleared, then error stated is removed.

Unlock screens stays as it is. It will have only shaking behavior if the attempt was unsuccessful.

@tschubotz could you please reflect it in product specs?
