### ISSUE TITLE
Replace recovery phrase stuck

### ISSUE THREAD

**Issue by denisgranha** [gnosis/safe-ios-legacy#684]
**Describe the bug**
I iniciated replace recovery phrase in the mobile app follow all the screens and reached a screen were no tx's was submited but the mobile was stuck.

**To Reproduce**
1. Start replace recovery phrase from the phone app. 
2. Copied the new mnemonic in a safe place
3. Entered 2 positions from the mnemonic, clicked next
4. Before confirming in the browser extension, click submit.
5. Confirm on the browser extension.
6. Submit button is not enabled in the phone app.

**Expected behavior**
Submit button should be available after I confirm the transaction from the browser extension, specially if it says, extension confirmed.

**Screenshots**
![IMG_0249](https://user-images.githubusercontent.com/4806080/56209417-c7abfc00-6053-11e9-9078-2d26ad4ac5a9.PNG)

**Smartphone (please complete the following information):**
 - Device: Iphone 6S Plus
 - iOS Version: 12.1
 - App Version 1.1.0

**Comment by DmitryBespalov** [comment]
see #650
