### ISSUE TITLE
StartViewController.swift line 68

### ISSUE THREAD

**Issue by gnosis-safe-ios-crashlytics** [gnosis/safe-ios-legacy#702]
#### in closure #1 in StartViewController.setupPassword(_:)

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/gnosis/ios/apps/io.gnosis.safe.adhoc/issues/5cbebfcbf8b88c2963f7671e?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/gnosis/ios/apps/io.gnosis.safe.adhoc/issues/5cbebfcbf8b88c2963f7671e?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by DmitryBespalov** [comment]
it was a test crash
