### ISSUE TITLE
Recovered safe can not sign and send transactions correctly

### ISSUE THREAD

**Issue by sche** [gnosis/safe-ios-legacy#718]
Issue:
The app was installed on top of the existing app (previous version) in which no safe was installed. After safe recovery, any transaction is not going through and failing with the "Invalid signatures" error.

Additionally, when trying to connect with browser extension, the pairing requests are executed OK by the server but the returned created pair is rejected by the app as invalid. Based on the code review, it should happen because the device pair does not contain either browser extension address (less probable) or device owner address, recovered from the "sender" signature of the pairing request.

Hypothesis:
The device address that the app is storing with the safe is not the same as the private key that is used as a 'device owner'

**Comment by DmitryBespalov** [comment]
The issue is that after refactoring, the Int enum order was changed and that caused wrong decoding of previously stored data with enum values meaning different things.
