### ISSUE TITLE
Check that app gets notifications after replacing recovery phrase

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-ios-legacy#741]
**Describe the bug**
Once it appeared to me that after replacing recovery phrase the app stopped receiving notifications from the extension.

**To Reproduce**
1. Have a safe with extension enabled
2. Replace the recovery phrase
3. Send any transaction
---
The 'confirmation' notification message does not come. App is always in "authentication required" state.

**Expected behavior**
The confirmation or rejection messages received successfully.

**Smartphone (please complete the following information):**
 - Device: iPhone 6s
 - iOS Version: 12.2
 - App Version 1.2.0 (development branch)

**Additional context**
Rinkeby network, Staging environment.

**Comment by sche** [comment]
I tested on iPhoneX and it works for me.
Use cases testes:
1) Recover safe with connected BE.
=> Test that incoming and outgoing transactions work well.
2) Replace recovery phrase
=> Test that incoming and outgoing transactions work well.
