### ISSUE TITLE
Crash in table view while dragging

### ISSUE THREAD

**Issue by gnosis-safe-ios-crashlytics** [gnosis/safe-ios-legacy#815]
#### in _CFArgv

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/gnosis/ios/apps/io.gnosis.safe/issues/5ceea07cf8b88c296339e70d?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/gnosis/ios/apps/io.gnosis.safe/issues/5ceea07cf8b88c296339e70d?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by DmitryBespalov** [comment]
Cannot reproduce right now, but I'll add the view controller breadcrumbs to each screen so that we know which screen was open during the crash.
