### ISSUE TITLE
Failed to register auth token because owner in response was different

### ISSUE THREAD

**Issue by gnosis-safe-ios-crashlytics** [gnosis/safe-ios-legacy#817]
#### in -801

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/gnosis/ios/apps/io.gnosis.safe/issues/5cef3621f8b88c296343f6cd?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/gnosis/ios/apps/io.gnosis.safe/issues/5cef3621f8b88c296343f6cd?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by DmitryBespalov** [comment]
Most probably happened because of the ​incorrect signature from the app. Will take a look if it will be repeated.
