### ISSUE TITLE
Cannot use GNO as payment token on Rinkeby

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-ios-legacy#832]
**Describe the bug**
I selected GNO as payment token and do hold GNO. But it wouldn't display the fee. :sob:

**To Reproduce**
1. Tap GNO (or ETH, or LOVE)
2. Select GNO as payment token
3. I am unable to continue to the review screen since the fee doesn't show up

**Expected behavior**
I can continue :)

**Screenshots**
<img src="https://user-images.githubusercontent.com/1380529/59095270-546a8c00-8918-11e9-8a4b-e3b35dd92a95.jpg" width=300px/>

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - iOS Version: 12.4
 - App Version: 1.3.0 (1) Pre-Production Rinkeby

**Additional context**
With LOVE and ETH it works like a charm.

**Comment by DmitryBespalov** [comment]
The GNO is not supported for Rinkeby right now, but @Uxio0 will add it.

**Comment by DmitryBespalov** [comment]
@tschubotz fixed.
