### ISSUE TITLE
Transactions view shows transactions not belonging to the safe

### ISSUE THREAD

**Issue by sche** [gnosis/safe-ios-legacy#837]
Lukas:
So after installing the Testflight version, I was taken to the Onboarding_CreateOrRestore screen. I went through the new Safe flow and after the creation fee it showed me the asset view but with transactions of my previous Safe that was active before the Testflight install. Don‘t think this is super critical but wanted to raise this.

**Comment by DmitryBespalov** [comment]
This is a critical issue. The problem is that the changes to our database handling code made the order of SQL fields different than it is in the existing apps, hence some fields are imported in a wrong way. I'll ship a fix soon. Unfortunately, I have to revoke the binary we submitted.

**Comment by DmitryBespalov** [comment]
fixed
