### ISSUE TITLE
DBTokeListItemRepository.swift line 62

### ISSUE THREAD

**Issue by gnosis-safe-ios-crashlytics** [gnosis/safe-ios-legacy#840]
#### in 

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/gnosis/ios/apps/io.gnosis.safe.prerelease/issues/07e78d93378a6aa6e8f74d9b3f95c672?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/gnosis/ios/apps/io.gnosis.safe.prerelease/issues/07e78d93378a6aa6e8f74d9b3f95c672?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by DmitryBespalov** [comment]
happened when installing 1.1.0 on top of the 1.3.0
