### ISSUE TITLE
Replace browser extension intro has text cutoff 

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-ios-legacy#864]
The text of the content is cut off, need to be full width

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/e360325b-26c3-46f9-ac0a-924c7dedb019" width=300/>

App version: 1.3.0 (3)
Device: iPhone XR

reported by @posthnikova

**Comment by posthnikova** [comment]
On Disconnect browser extension text also needs to be full width:

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/8bd43473-70f9-4b90-9116-6b956ea4593a)

Illustration needs to be replaced by updated one from Connect browser: zpl.io/b64dOkP
