### ISSUE TITLE
DBTransactionRepository.swift line 199

### ISSUE THREAD

**Issue by gnosis-safe-ios-crashlytics** [gnosis/safe-ios-legacy#869]
#### in 

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/gnosis/ios/apps/io.gnosis.safe/issues/6b0fa4833a917672d92ce8e7341e53c2?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/gnosis/ios/apps/io.gnosis.safe/issues/6b0fa4833a917672d92ce8e7341e53c2?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by DmitryBespalov** [comment]
This is an old one (1.0.1)
