### ISSUE TITLE
Review the logs sent out to Crashlytics

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-ios-legacy#873]
Review to minimize the sensitive information sent.

Document the information collected.

Dependent on the ​data protection team.

**Comment by DmitryBespalov** [comment]
## Where the data is sent?
- To Firebase (Crashlytics) - 3rd party service

## What data is sent?
In addition to crash report and device information that is collected by the Crashlytics service automatically, we added logging of:

- Wallet address
- Screen names that led to the opening of the last screen.

This would allow improving app stability by providing us more information about the context of errors and crashes.

## When data is sent?
- When crash occurs
- When safe creation fails because safe creation transaction fails
- When safe creation fails because of Gnosis backend service failure

**Comment by tschubotz** [comment]
That's actually already mentioned in the data protection sheet (cell B26) so all good:) https://docs.google.com/spreadsheets/d/1i8BY8M7f9wReZcMVDHGrGvtMC7r4z2kJ1-JlDrpiQB4/edit#gid=0

**Comment by tschubotz** [comment]
Ah no, the wallet address is missing. I'll add it and let the data protection team know.
