### ISSUE TITLE
Safe recovery: entering a safe address with no internet connect shows wrong error

### ISSUE THREAD

**Issue by sche** [gnosis/safe-ios-legacy#895]
**Describe the bug**
Safe recovery: entering a safe address with no internet connect shows "Address is invalid" error.
This message is confusing.

**To Reproduce**
1. Start Safe recovery process.
2. Turn of internet.
3. Scan Safe address
=> wrong error message.

**Comment by DmitryBespalov** [comment]
@sche which error message should it be?
