### ISSUE TITLE
SecureExternallyOwnedAccountRepository.swift line 22

### ISSUE THREAD

**Issue by gnosis-safe-ios-crashlytics** [gnosis/safe-ios-legacy#907]
#### in 

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/gnosis/ios/apps/io.gnosis.safe/issues/e27f1d42c95720f99b20ea231c6b0234?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/gnosis/ios/apps/io.gnosis.safe/issues/e27f1d42c95720f99b20ea231c6b0234?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by DmitryBespalov** [comment]
fixed by https://github.com/gnosis/safe-ios/pull/949
