### ISSUE TITLE
After Touch ID being incorrect 3 times it no longer accepts touch ID

### ISSUE THREAD

**Issue by denisgranha** [gnosis/safe-ios-legacy#923]
**Describe the bug**
When touch ID is invalid 3 times. Keyboard input pop's up and even after clicking touch id button and being correct, it will enforce to enter keyboard password.

**To Reproduce**
1. Open the app so Touch ID is shown.
2. Enter a wrong fingerprint 3 times
3. Click on the touch ID button
4. Enter a correct fingerprint

**Expected behavior**
After step 4, the app should log in, without enforce keyboard input of password.

**Smartphone (please complete the following information):**
 - Device: Iphone 6s plus
 - iOS Version: 12.2
 - App Version 1.3.1

**Comment by DmitryBespalov** [comment]
Thanks. After 3 unsuccessful touch ids we enforce password for security reason. The app should not show touch id icon after 3 wrong fingerprints though.

**Comment by DmitryBespalov** [comment]
After 5 invalid touch id entries, the iPhone blocks the Touch ID and it becomes unavailable. 

current dev version works as expected.
