### ISSUE TITLE
TransferViewCell should show full amount

### ISSUE THREAD

**Issue by sche** [gnosis/safe-ios-legacy#928]
Currently amount to transfer is formatted and thus is not visible completely.
![2019-06-28_16-30-00](https://user-images.githubusercontent.com/2284385/60349572-2da4f000-99c2-11e9-83aa-ec17011b7096.png)

**Comment by DmitryBespalov** [comment]
This is yet to be discussed with product owner and designer team. 

https://github.com/gnosis/safe/issues/202
