### ISSUE TITLE
Firebase tokens getting invalid but the app doesn't receive new tokens from Firebase

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-ios-legacy#980]
Sometimes in the production app the token becomes invalid (happened after updating from previous version to new version of the app), and then the push notifications stop working.

We need to find a way to detect invalid tokens on the client and force-update them.

**Comment by sche** [comment]
I have created a support ticket in Firebase with the problem description.
Let's wait for the answer.

One of the alternative ideas I have:
Do not use InstanceID.instanceID().instanceID and always rely on our storage & didReceiveRegistrationToken method.
