### ISSUE TITLE
WC JSON RPC failed to decode valid response object from string

### ISSUE THREAD

**Issue by gnosis-safe-ios-crashlytics** [gnosis/safe-ios-legacy#983]
#### in 

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/gnosis/ios/apps/io.gnosis.safe/issues/e6311dbcb0afb42684d85e0687f376a0?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/gnosis/ios/apps/io.gnosis.safe/issues/e6311dbcb0afb42684d85e0687f376a0?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by DmitryBespalov** [comment]
failed to decode `{"jsonrpc":"2.0","id":1563895837415317,"result":null}`

**Comment by DmitryBespalov** [comment]
not critical
