### ISSUE TITLE
Crash in Server.swift

### ISSUE THREAD

**Issue by gnosis-safe-ios-crashlytics** [gnosis/safe-ios-legacy#984]
#### in 

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/gnosis/ios/apps/io.gnosis.safe/issues/6407b87b534b5687a32ee6527bdb2c37?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/gnosis/ios/apps/io.gnosis.safe/issues/6407b87b534b5687a32ee6527bdb2c37?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by DmitryBespalov** [comment]
Crash happened when delegate was deallocated (nil), but the app tried to access it.

There are multiple similar places in the code when this is the case.

**Comment by DmitryBespalov** [comment]
after analyzing the source code, it is highly unlikely that crash is in the access to delegate (forced unwrap), or in `try! reconnect()`. 

We suspect that the issue is with thread racing for access to `sessions` variable.

happened on iOS 13.
